import type { Restaurant } from "@/types"

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Nhà Hàng Việt Phố",
    location: "123 Lê Lợi, Quận 1, TP.HCM",
    description: "Nhà hàng Việt Nam truyền thống với không gian ấm cúng",
    rating: 4.5,
    openingHours: {
      open: "07:00",
      close: "22:00",
    },
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    dishes: [
      {
        id: "1",
        name: "Phở Bò Tái",
        description: "Phở bò truyền thống với nước dùng đậm đà, thịt bò tái và các loại rau thơm",
        price: 85000,
        image: "/placeholder.svg?height=300&width=400",
        category: "Món súp",
        isFeatured: true,
      },
      {
        id: "2",
        name: "Bánh Mì Thịt Nướng",
        description: "Bánh mì giòn với thịt nướng, rau củ và sốt đặc biệt",
        price: 45000,
        image: "/placeholder.svg?height=300&width=400",
        category: "Món nhanh",
        isFeatured: false,
      },
      {
        id: "3",
        name: "Gỏi Cuốn Tôm Thịt",
        description: "Gỏi cuốn tươi mát với tôm, thịt heo, bún và rau sống",
        price: 65000,
        image: "/placeholder.svg?height=300&width=400",
        category: "Khai vị",
        isFeatured: false,
      },
      {
        id: "4",
        name: "Cơm Tấm Sườn Nướng",
        description: "Cơm tấm với sườn nướng, bì, chả, trứng ốp la và đồ chua",
        price: 75000,
        image: "/placeholder.svg?height=300&width=400",
        category: "Món chính",
        isFeatured: false,
      },
      {
        id: "5",
        name: "Chè Ba Màu",
        description: "Chè ba màu truyền thống với đậu, nước cốt dừa và đá bào",
        price: 35000,
        image: "/placeholder.svg?height=300&width=400",
        category: "Tráng miệng",
        isFeatured: false,
      },
    ],
    priceRange: undefined
  },
  {
    id: "2",
    name: "Quán Ăn Ngon",
    location: "456 Nguyễn Huệ, Quận 1, TP.HCM",
    description: "Quán ăn bình dân với đa dạng món ăn Việt Nam",
    rating: 4.2,
    openingHours: {
      open: "06:00",
      close: "23:00",
    },
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    dishes: [
      {
        id: "6",
        name: "Bún Chả Hà Nội",
        description: "Bún chả với thịt nướng, chả giò, nước mắm pha và rau sống",
        price: 70000,
        image: "/placeholder.svg?height=300&width=400",
        category: "Món chính",
        isFeatured: true,
      },
      {
        id: "7",
        name: "Bánh Xèo",
        description: "Bánh xèo giòn với tôm, thịt, giá đỗ và rau sống",
        price: 60000,
        image: "/placeholder.svg?height=300&width=400",
        category: "Món chính",
        isFeatured: false,
      },
      {
        id: "8",
        name: "Gỏi Ngó Sen Tôm Thịt",
        description: "Gỏi ngó sen tươi mát với tôm, thịt heo và các loại rau thơm",
        price: 55000,
        image: "/placeholder.svg?height=300&width=400",
        category: "Khai vị",
        isFeatured: false,
      },
      {
        id: "9",
        name: "Cà Phê Sữa Đá",
        description: "Cà phê đen đậm đà pha với sữa đặc và đá",
        price: 30000,
        image: "/placeholder.svg?height=300&width=400",
        category: "Đồ uống",
        isFeatured: false,
      },
      {
        id: "10",
        name: "Sinh Tố Bơ",
        description: "Sinh tố bơ béo ngậy với sữa đặc và đá bào",
        price: 40000,
        image: "/placeholder.svg?height=300&width=400",
        category: "Đồ uống",
        isFeatured: false,
      },
    ],
    priceRange: undefined
  },
]

